name: Deploy to App Engine

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Decode and export GCP credentials
      run: echo '${{ secrets.GCP_SA_KEY }}' > $HOME/gcp-key.json
  
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: $HOME/gcp-key.json
    
    - name: Deploy to App Engine
      run: |
        gcloud app deploy --quiet
